[template]

[placeholders]
gh-username = { type = "string", prompt = "GitHub 用户名" }

[placeholders.init-script]
type = "bool"
prompt = "是否执行初始化脚本（安装开发工具）"
default = true

[hooks]
post = [
    "init-hook.rhai"
]
